# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5PsqEcJhn_rXEmfZu13OmZIHjmeG0Tz
"""

# =========================================
# 🌳 Streamlit Dashboard: กิจกรรมในสวนสาธารณะกรุงเทพฯ
# =========================================

import streamlit as st
import pandas as pd
import altair as alt

# ตั้งค่าหน้าเว็บ
st.set_page_config(page_title="สิ่งอำนวยความสะดวกในสวนสาธารณะกรุงเทพฯ", layout="wide")
st.title("🌳 Top 5 สวนสาธารณะที่มีสิ่งอำนวยความสะดวกมากที่สุดในกรุงเทพฯ")

# โหลดข้อมูล CSV
@st.cache_data
def load_data():
    df = pd.read_csv("parks_activities.csv")
    df.columns = df.columns.str.strip()
    df["name"] = df["name"].astype(str).str.strip()
    df = df[df["name"].notna()]
    df = df[~df["name"].isin(["รวม", ""])]
    return df

df = load_data()

# ทำความสะอาดและคำนวณยอดรวม
activity_cols = [c for c in df.columns if c not in ["name", "ยอดรวม"]]
df["ยอดรวมคำนวณ"] = df[activity_cols].sum(axis=1)
df["ยอดรวม"] = df[["ยอดรวม", "ยอดรวมคำนวณ"]].max(axis=1).astype(int)

# ---------- ส่วนสรุปด้านบน ----------
n_parks = df["name"].nunique()  # นับจำนวนสวนทั้งหมด
avg_activities = df["ยอดรวม"].mean()

colA, colB = st.columns(2)
with colA:
    st.metric("จำนวนสวนทั้งหมด", f"{n_parks}")
with colB:
    st.metric("กิจกรรมเฉลี่ยต่อสวน", f"{avg_activities:.1f}")

# ---------- สร้าง Lollipop Chart ----------
top5 = df.sort_values("ยอดรวม", ascending=False).head(5)

lollipop = alt.layer(
    alt.Chart(top5).mark_rule(stroke="#43a047", strokeWidth=6).encode(
        y=alt.Y("name:N", sort="-x", title="ชื่อสวน"),
        x=alt.X("ยอดรวม:Q", title="จำนวนกิจกรรม")
    ),
    alt.Chart(top5).mark_circle(size=250, color="#2e7d32").encode(
        y=alt.Y("name:N", sort="-x"),
        x="ยอดรวม:Q",
        tooltip=list(top5.columns)
    )
).properties(title="🍭 สวนที่มีสิ่งอำนวยความสะดวกมากที่สุด (Top 5)", height=350)

st.altair_chart(lollipop, use_container_width=True)

# ---------- แสดงการ์ดรายละเอียดแต่ละสวน ----------
st.subheader("🏞️ รายละเอียดสิ่งอำนวยความสะดวกในแต่ละสวน (Top 5)")

for _, row in top5.iterrows():
    activities = [col for col in activity_cols if row[col] == 1]

    st.markdown(f"""
    <div style="
        background-color: #5DD39E;
        border-radius: 20px;
        padding: 20px;
        margin-bottom: 20px;
        color: black;
        font-family: 'TH Sarabun New', sans-serif;
    ">
        <h4 style="margin-bottom: 10px;"><b>{row['name']}</b></h4>
        <p style="margin-bottom: 5px;">สิ่งอำนวยความสะดวกและกิจกรรม:</p>
        <ul style="margin-top: 0;">
            {''.join([f'<li>{a}</li>' for a in activities])}
        </ul>
        <p style="margin-top: 10px;"><b>รวมทั้งหมด:</b> {int(row['ยอดรวม'])} รายการ</p>
    </div>
    """, unsafe_allow_html=True)
